name: weather_app
description: "Flutter Weather Project"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

  flutter_lints: ^4.0.0

flutter:
 
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/Gidole-Regular.ttf


  fonts:
    - family: Gidole
      fonts:
        - asset: assets/fonts/Gidole-Regular.ttf


  